<?php
$file = 'c:\xampp\htdocs\bundling2\resources\views\bpjs\bridginginacbg2.blade.php';
$content = file_get_contents($file);

$target1 = "                    <!-- Tombol Lihat Resume -->\r\n                    @if(\$resume)\r\n                    <button type=\"button\" class=\"btn-eklaim btn-info\" data-toggle=\"modal\" data-target=\"#modalLihatResume\" style=\"color:white;\">\r\n                        <i class=\"fas fa-file-medical\"></i> Lihat Resume\r\n                    </button>\r\n                    @endif\r\n\r\n                    <!-- Tombol Data Triase (Ranap only) -->\r\n                    @if(\$pasien->status_lanjut == 'Ranap' && \$triase)\r\n                    <button type=\"button\" class=\"btn-eklaim\" data-toggle=\"modal\" data-target=\"#modalTriase\" style=\"background:#6f42c1;color:white;\">\r\n                        <i class=\"fas fa-heartbeat\"></i> Data Triase\r\n                    </button>\r\n                    @endif";

$replacement1 = "                    <!-- Tombol Lihat Resume -->\r\n                    <button type=\"button\" class=\"btn-eklaim btn-info\" onclick=\"openResumeModal(this, '{{ \$pasien->no_rawat }}')\" style=\"color:white;\">\r\n                        <i class=\"fas fa-file-medical\"></i> Lihat Resume\r\n                    </button>\r\n\r\n                    <!-- Tombol Data Triase (Ranap only) -->\r\n                    @if(\$pasien->status_lanjut == 'Ranap')\r\n                    <button type=\"button\" class=\"btn-eklaim\" onclick=\"openTriaseModal(this, '{{ \$pasien->no_rawat }}')\" style=\"background:#6f42c1;color:white;\">\r\n                        <i class=\"fas fa-heartbeat\"></i> Data Triase\r\n                    </button>\r\n                    @endif";

$content = str_replace($target1, $replacement1, $content);

$target2 = "<!-- MODAL DATA TRIASE (INCLUDED) -->\r\n@if(\$pasien->status_lanjut == 'Ranap' && \$triase)\r\n    @include('bpjs.component._modal_triase')\r\n@endif\r\n<!-- MODAL LIHAT RESUME (INCLUDED) -->\r\n@if(\$resume)\r\n    @include('bpjs.component._modal_resume')\r\n@endif";

$replacement2 = "<div id=\"modalContainer\"></div>\r\n\r\n<script>\r\nfunction openTriaseModal(btn, norawat) {\r\n    var originalHtml = btn.innerHTML;\r\n    btn.innerHTML = '<i class=\"fas fa-spinner fa-spin\"></i>';\r\n    btn.disabled = true;\r\n\r\n    $.ajax({\r\n        url: '{{ route(\"inacbg.getTriaseModalHtml\") }}',\r\n        type: 'GET',\r\n        data: { norawat: norawat },\r\n        success: function(response) {\r\n            btn.innerHTML = originalHtml;\r\n            btn.disabled = false;\r\n            \r\n            $('#modalContainer').html(response.html);\r\n            $('#modalTriase').modal('show');\r\n        },\r\n        error: function(xhr) {\r\n            btn.innerHTML = originalHtml;\r\n            btn.disabled = false;\r\n            var errMsg = 'Terjadi kesalahan sistem';\r\n            if (xhr.responseJSON && xhr.responseJSON.message) {\r\n                errMsg = xhr.responseJSON.message;\r\n            } else if (xhr.responseJSON && xhr.responseJSON.error) {\r\n                errMsg = xhr.responseJSON.error;\r\n            }\r\n            Swal.fire('Error', errMsg, 'error');\r\n        }\r\n    });\r\n}\r\n\r\nfunction openResumeModal(btn, norawat) {\r\n    var originalHtml = btn.innerHTML;\r\n    btn.innerHTML = '<i class=\"fas fa-spinner fa-spin\"></i>';\r\n    btn.disabled = true;\r\n\r\n    $.ajax({\r\n        url: '{{ route(\"inacbg.getResumeModalHtml\") }}',\r\n        type: 'GET',\r\n        data: { norawat: norawat },\r\n        success: function(response) {\r\n            btn.innerHTML = originalHtml;\r\n            btn.disabled = false;\r\n            \r\n            $('#modalContainer').html(response.html);\r\n            $('#modalLihatResume').modal('show');\r\n        },\r\n        error: function(xhr) {\r\n            btn.innerHTML = originalHtml;\r\n            btn.disabled = false;\r\n            var errMsg = 'Terjadi kesalahan sistem';\r\n            if (xhr.responseJSON && xhr.responseJSON.message) {\r\n                errMsg = xhr.responseJSON.message;\r\n            } else if (xhr.responseJSON && xhr.responseJSON.error) {\r\n                errMsg = xhr.responseJSON.error;\r\n            }\r\n            Swal.fire('Error', errMsg, 'error');\r\n        }\r\n    });\r\n}\r\n</script>";

$content = str_replace($target2, $replacement2, $content);

file_put_contents($file, $content);
echo "Done!\n";
?>
